#!/bin/sh
#
# z3bra - 2014 (c) wtfpl
# toggle the fullscreen state of a window
# depends on: focus.sh

# it's pretty simple, but anyway...
usage() {
    echo "usage: $(basename $0) <wid>"
    exit 1
}

# exit if no argument given
test -z "$1" && usage
# if not, then put the current window in fullscreen mode, after saving its
# geometry and id to $FSFILE we also remove any border from this window.
wattr xywhi $1 > $FSFILE
chwb -s 0 $1
wtp $(wattr xywh `lsw -r`) $1

# now focus the window, and put it in front, no matter which state we're in, and
# put the cursor on its bottom-right corner (for consistency)
focus $1
