#!/bin/sh

#Put links to videos in the text file. Save & quit once you are done.
$EDITOR ~/download.txt
youtube-dl $1 --verbose -ci --batch-file=download.txt --proxy socks://localhost:9050
rm download.txt
