#!/bin/sh
#Taken from https://sattlers.org/2019/09/30/ffmpeg-split-and-cut-video-segments/
# Usage: split "input" segment-length-in-seconds

ffmpeg -i "$1" -c:v libx264 -crf 22 -map 0 -segment_time $2 -g 9 -sc_threshold 0 -force_key_frames "expr:gte(t,n_forced*9)" -reset_timestamps 1 -f segment "segment_%03d.$1"
